USE DataBaseLaba

DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS GROUPS;
DROP TABLE IF EXISTS DISCIPLINES;
DROP TABLE IF EXISTS STUDENTS_MARKS;

CREATE TABLE DISCIPLINES (
	IDdiscipline INT IDENTITY PRIMARY KEY,
	DisciplineName NVARCHAR (50)NOT NULL UNIQUE,
);

CREATE TABLE GROUPS (
	IDGroup INT IDENTITY PRIMARY KEY,
	GroupName NVARCHAR (20)NOT NULL,
	Сourse INT NOT NULL,
	Semester INT NOT NULL,
);

CREATE TABLE STUDENTS (
	IDstudent INT IDENTITY PRIMARY KEY,
	Surname NVARCHAR (50)NOT NULL,
	FirstName NVARCHAR(50)NOT NULL,
	Patronymic NVARCHAR (50)NOT NULL,
	Gender NVARCHAR (10)NOT NULL,
	Birthday DATE NOT NULL,
	RegistrationAddress NVARCHAR (100)NOT NULL,
	GroupID INT NOT NULL,
	CONSTRAINT StudentsGroupID FOREIGN KEY (GroupID) REFERENCES GROUPS(IDGroup)ON DELETE CASCADE,
	CONSTRAINT StudentUnique UNIQUE (Surname, FirstName, Patronymic, Gender, Birthday, RegistrationAddress)
);

CREATE TABLE STUDENTS_MARKS (
	IDstudent_mark INT IDENTITY PRIMARY KEY,
	StudentID INT NOT NULL,
	DisciplineID INT NOT NULL,
	Student_Mark INT NOT NULL,
	CONSTRAINT StudID FOREIGN KEY (StudentID) REFERENCES STUDENTS(IDstudent)ON DELETE CASCADE,
	CONSTRAINT DiscipID FOREIGN KEY (DisciplineID) REFERENCES DISCIPLINES(IDdiscipline)ON DELETE CASCADE,
	CONSTRAINT StudUnique UNIQUE (StudentID, DisciplineID, Student_Mark)
);
